apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: test-deployment
spec:
  selector:
    app: spring-boot     
  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080